name: run

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  tests:
    name: unit-tests
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run ZKsync OS
        id: zks
        uses: dutterbutter/zksync-server-action@db/add-log-outputs
        with:
          version: latest
          anvil_logs: true
          zksync_logs: true

      - name: Print Anvil log
        if: always()
        run: cat ${{ steps.zks.outputs.anvil_log_path }}

      - name: Print server log
        if: always()
        run: cat ${{ steps.zks.outputs.zksync_log_path }}
            
      - name: Install Foundry-ZKsync
        uses: dutterbutter/foundry-zksync-toolchain@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: |
          yarn ci:tests


      - name: Upload Anvil-zksync Log
        uses: actions/upload-artifact@v4
        with:
          name: anvil_zksync-log
          path: anvil_zksync.log