name: run

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  tests:
    name: unit-tests
    strategy:
      matrix:
        platform: [ubuntu-20.04, ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run anvil-zksync
        uses: dutterbutter/anvil-zksync-action@db/debugging
        with:
          mode: fork
          forkUrl: mainnet
          log: info
          logFilePath: anvil_zksync.log
          target: x86_64-unknown-linux-gnu
          releaseTag: latest

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: |
          yarn ci:tests
