name: run

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  tests:
    name: unit-tests
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Era Test Node
        uses: dutterbutter/anvil-zksync-action@db/anvil-zksync-repo-rename
        with:
          mode: fork
          forkUrl: mainnet
          logFilePath: "anvil_zksync.log"

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: |
          yarn ci:tests

      - name: Upload Anvil ZKSYNC Log
        uses: actions/upload-artifact@v3
        with:
          name: anvil_zksync-log
          path: anvil_zksync.log
